move defaults to registrar
openedx-unsupported/registrar pull request #119
Opened 2019-06-03 13:29 UTC by syed-awais-ali

## Description

TODO: Include a detailed description of the changes in the body of the PR

2019-06-03 15:01 UTC, kdmccormick requested changes
Reviewing now

2019-06-03 15:09 UTC, kdmccormick approved these changes
Pending the once change I requested, this looks good to me.

2019-06-03 15:09 UTC, kdmccormick commented on registrar/settings/base.py
> +MEDIA_STORAGE_BACKEND = {
`MEDIA_STORAGE_BACKEND` isn't an actual setting; it's an edX-configuration-specific dict we unpack [here](https://github.com/edx/registrar/blob/master/registrar/settings/production.py#L35), so this is a no-op.

We already set the media storage defaults [here](https://github.com/edx/registrar/blob/master/registrar/settings/base.py#L134-L137), so you can safely delete this dict :)

2019-06-03 21:12 UTC, adzuci approved these changes

2019-06-03 21:12 UTC, adzuci commented on registrar/settings/base.py
> +API_ROOT = 'http://localhost:18734/api'
I don't have enough context to have a strong oppinion, but I'm curious if we should default to a running local configuration or if it's ok to have a few `<replaceme>`s and allow the community to plug in what's needed?

2019-06-03 21:19 UTC, kdmccormick commented on registrar/settings/base.py
> +API_ROOT = 'http://localhost:18734/api'
Having `localhost:port` baked in here will make things more likely to "just work" if someone spins up Registrar in devstack for the first time, and I think there's value in that. However, you could definitely argue that such devstack-specific configuration should instead be put in devstack, which would reap the same benefits while also avoiding mixing together config from different parts of our ecosystem.

In the end, though, I'm so confused about our overall configuration strategy that I don't have a strong opinion either.

2019-06-03 21:20 UTC, kdmccormick commented on registrar/settings/base.py
> +API_ROOT = 'http://localhost:18734/api'
I think the best compromise at the moment would be putting devstack-specific stuff in Registrar's `devstack.py` and putting `replace-me`s in `base.py`

2019-06-12 14:15 UTC, kdmccormick approved these changes
@syed-awais-ali  Looks good -- the only change I request is that you keep `API_ROOT = http://replace-me/api` in `base.py` and override as:
* `API_ROOT = 'http://localhost:18734/api'` in `devstack.py`
* `API_ROOT = 'http://localhost:8000/api'` in `local.py`

2019-06-14 11:44 UTC, syed-awais-ali commented
@kdmccormick We already have `API_ROOT = 'http://localhost:18734/api'` in local.py. I have override it in devstack.py and replaced the string in base.py.

2019-06-14 11:54 UTC, syed-awais-ali commented
We already have `API_ROOT = 'http://localhost:18734/api'` in local.py and not `API_ROOT = 'http://localhost:8000/api'`
Added `API_ROOT = 'http://localhost:18734/api'` to the devstack.py.
@kdmccormick please can you again take a look at this. Thanks

2019-06-14 14:31 UTC, kdmccormick commented
Thanks for adding `API_ROOT = 'http://localhost:18734/api'` to devstack.py.

The `API_ROOT = 'http://localhost:18734/api'` in local.py is a mistake; please change it to `API_ROOT = 'http://localhost:8000/api'`, and then you have my go-ahead to squash and merge!

2019-06-17 12:20 UTC, kdmccormick approved these changes
Thanks @syed-awais-ali ! Go ahead and sqaush & merge

2019-06-17 12:20 UTC, merged