csv upload endpoints
openedx-unsupported/registrar pull request #131
Opened 2019-06-18 18:29 UTC by Zacharis278

### [EDUCATOR-4335](https://openedx.atlassian.net/browse/EDUCATOR-4335)

* endpoints to upload program/course enrollments via csv
* added a 5 MiB upper limit on file size jic

2019-06-19 16:09 UTC, Zacharis278 commented
added in a fix for the filestore differences between s3 and local storage
> https://github.com/edx/registrar/pull/131/files#diff-2213b9fd93196ca1860ba79af3cc5fc2R57

2019-06-20 13:02 UTC, kdmccormick reviewed
Looks great! Two smallish comments.

2019-06-20 13:02 UTC, kdmccormick commented on registrar/apps/enrollments/tasks.py
> +    pass
I'd change this to fail with message "not implemented" so that we don't accidentally put a program in a locked state.

2019-06-20 13:02 UTC, kdmccormick commented on registrar/apps/api/v1/views.py
> +
Nit: For "abstract" classes like this, I like throwing something like `task_fn = None  # Override in subclass` in the body to make it clear which members need to get overridden.

2019-06-20 13:25 UTC, Zacharis278 commented on registrar/apps/enrollments/tasks.py
> +    pass
that's a very good point.

2019-06-20 15:05 UTC, kdmccormick requested changes
Code looks good other than a final nit.

However I get a 500 when I POSTed without a file or a trailing slash:
```
RuntimeError at /api/v1/programs/gtmasters/enrollments/upload

You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to localhost:18734/api/v1/programs/gtmasters/enrollments/upload/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
```

2019-06-20 15:05 UTC, kdmccormick commented on registrar/apps/api/v1/views.py
> +
Also `field_names`

2019-06-20 17:20 UTC, kdmccormick approved these changes
:zap:

2019-06-20 17:23 UTC, merged