Add a trivial v2 API.
openedx-unsupported/registrar pull request #147
Opened 2019-06-28 18:54 UTC by iloveagent57

In support of releasing a new partner integration guide, we're releasing a v2 of the API that simply imports all of the URL patterns from v1.

https://openedx.atlassian.net/browse/EDUCATOR-4441

2019-06-28 19:02 UTC, zacharis278 approved these changes
💃

2019-06-28 19:07 UTC, kdmccormick requested changes
Nice. Can you update `api.yaml` too?

2019-06-28 19:19 UTC, kdmccormick commented
@iloveagent57 also, can you update [this](https://github.com/edx/registrar/blob/master/registrar/apps/api/v1/mixins.py#L224) so that `job_url`s point to the V2 API?

2019-06-28 19:27 UTC, schenedx reviewed
Do you need a change in api.yaml file as well?

2019-06-28 19:50 UTC, jansenk commented on registrar/apps/api/v2/urls.py
> +urlpatterns = [pattern for pattern in v1_urlpatterns]
nit: do you even need to do this? could you just do `urlpatterns = v1_urlpatterns`?

2019-06-28 19:53 UTC, jansenk commented
would we also want to make a change to the values of `event_method_map`? They specify v1

2019-06-28 20:15 UTC, iloveagent57 commented on registrar/apps/api/v2/urls.py
> +urlpatterns = [pattern for pattern in v1_urlpatterns]
No, it's definitely not required - I left that as a sort of breadcrumb for when we have to pick and choose which patterns we want from v1 and which ones we need to explicitly define in v2.

2019-06-28 20:17 UTC, iloveagent57 commented
Ooh, that `event_method_map` thing is a good point, so is that JobStatusMixin thing - I think this might be a little more involved than I initially thought.  I'm going to work on refactoring this out a little bit to see if I can make it more consistent regardless of which set of endpoints you actually hit.

2019-07-01 15:29 UTC, schenedx approved these changes
👍 LGTM. We would need some comprehensive testing for this on Stage, I'd say.

2019-07-01 17:04 UTC, kdmccormick approved these changes
Nice!

2019-07-01 17:23 UTC, merged