command to create or modify programs
openedx-unsupported/registrar pull request #157
Opened 2019-07-12 16:17 UTC by jansenk

`./manage.py manage_programs org_key <discovery_uuid>:<program_key>*`

2019-07-12 16:26 UTC, kdmccormick commented
Preliminary comment -- we wrote the Jenkins and Ansible not to pass the `org_key` into this command. If there's a way to avoid taking in the `org_key`, then that would save us from changing that work.

2019-07-15 15:42 UTC, jansenk commented
No longer require org_key, now we look at the authoring_organizations on the program and use the first one we also have in Registrar

2019-07-15 16:43 UTC, zacharis278 requested changes
Looks good just one comment.  If we're gonna assign the first matching organization to every program can we add a comment to make that decision more obvious?

2019-07-16 16:21 UTC, zacharis278 approved these changes

2019-07-16 17:42 UTC, merged