Add OrgGroups and roles
openedx-unsupported/registrar pull request #21
Opened 2019-03-08 20:04 UTC by jansenk

https://openedx.atlassian.net/browse/EDUCATOR-4151

Add OrgGroups
Add Organization permissions and roles
Tests

2019-03-11 17:50 UTC, zacharis278 approved these changes
lgtm

2019-03-11 18:07 UTC, kdmccormick commented on registrar/apps/api/v1/tests/test_views.py
> +from registrar.apps.enrollments.tests.factories import (  # pylint: disable=no-name-in-module
pylint passes for me without these `no-name-in-module` suppressions. Was pylint failing locally for you, or on jenkins, or both?

2019-03-11 18:09 UTC, jansenk commented on registrar/apps/api/v1/tests/test_views.py
> +from registrar.apps.enrollments.tests.factories import (  # pylint: disable=no-name-in-module
It was failing for me locally

2019-03-11 18:13 UTC, kdmccormick requested changes
Looks good other than the comments I left.

2019-03-11 18:13 UTC, kdmccormick commented on registrar/apps/enrollments/models.py
> +    organization = models.ForeignKey(Organization, on_delete=models.CASCADE)
If we're doing `organization = None` for global permissions, we need `null=True` here, along with a comment saying so.

Additionally, `OrgGroup.save` will need to be tweaked, and we should have a test verifying that `organization = None` implies global permissions.

2019-03-11 18:13 UTC, kdmccormick commented on registrar/apps/api/v1/tests/test_views.py
> +from registrar.apps.enrollments.tests.factories import (  # pylint: disable=no-name-in-module
pylint passes for me without these `no-name-in-module` suppressions. Was pylint failing locally for you, or on jenkins, or both?

2019-03-11 18:18 UTC, kdmccormick commented on registrar/apps/enrollments/models.py
> +class OrgGroup(Group):
If there's a way to remove the `Permissions` dialog from the admin panel, that'd be a good thing to do.

2019-03-11 18:20 UTC, kdmccormick commented on registrar/apps/enrollments/models.py
> +        (perms.OrganizationReadMetadataRole.name, 'Read an Organization Metadata'),
I recommend changing this to `'Read Metadata Only'`, because:
* It's program metadata they're reading, not organization metadata
* Having `'Only'` in the name hints that the other two roles allow metadata reading too

2019-03-11 18:27 UTC, schenedx commented on registrar/apps/enrollments/models.py
> +    organization = models.ForeignKey(Organization, on_delete=models.CASCADE)
For the statement:
`If we're doing organization = None for global permissions, we need null=True here, along with a comment saying so.`, I thought we just won't have a data row into this table if the group created is not limited to any organization, right?

2019-03-11 18:28 UTC, iloveagent57 commented on registrar/apps/enrollments/models.py
> +    organization = models.ForeignKey(Organization, on_delete=models.CASCADE)
That's right, Simon - we'll use vanilla `auth_group` records for global perms - every `OrgGroup` should have a non-null organization.

2019-03-11 18:31 UTC, schenedx reviewed
suggested one more test case.

2019-03-11 18:31 UTC, schenedx commented on registrar/apps/enrollments/tests/test_models.py
> +    def test_roles(self, role):
Can we have another test to specifically make sure, if a user is created and saved into org 1, it do not have permissions for any permissions on org 2?

2019-03-11 18:32 UTC, iloveagent57 commented on registrar/apps/enrollments/models.py
> +class OrgGroup(Group):
Let the great debate of our time begin: `OrgGroup`, `OrganizationGroup`, or something else?  `AccessControlGroup`?  Also, does this belong in the `enrollments` app or the `core` app?  I think I can make a pretty good case that it belongs in `core`.

2019-03-11 18:33 UTC, schenedx commented on registrar/apps/enrollments/models.py
> +class OrgGroup(Group):
I suggest `core` as well. I can see we have different django app for different data set to proxy with

2019-03-11 18:42 UTC, jansenk commented on registrar/apps/api/v1/tests/test_views.py
> +from registrar.apps.enrollments.tests.factories import (  # pylint: disable=no-name-in-module
Yeah, this was failing for me locally

2019-03-11 18:44 UTC, kdmccormick commented on registrar/apps/enrollments/models.py
> +class OrgGroup(Group):
My vote is `OrganizationGroup`.

I think it belongs in `core`, but then `Organization` should also be moved to `core`. `core` shouldn't be importing from `enrollments`.

2019-03-11 20:03 UTC, kdmccormick commented on registrar/apps/enrollments/models.py
> +    organization = models.ForeignKey(Organization, on_delete=models.CASCADE)
Sounds good; my misunderstanding.

2019-03-12 13:09 UTC, schenedx commented on registrar/apps/enrollments/models.py
> +class OrgGroup(Group):
@kdmccormick I agree we should move Organization out of enrollment app. 
Can we just create a new ticket to do the move instead of adding scope to this PR? @jansenk do you mind creating the ticket to capture the conversation above?

2019-03-12 17:34 UTC, schenedx commented on registrar/apps/enrollments/models.py
> +class OrgGroup(Group):
@jansenk I already created the move ticket at https://openedx.atlassian.net/browse/EDUCATOR-4184

2019-03-13 16:16 UTC, schenedx approved these changes
👍

2019-03-13 16:54 UTC, merged