Add read program reports role
openedx-unsupported/registrar pull request #221
Opened 2019-12-11 21:00 UTC by how015

MST-50:
In order to provide user access to reports, we need to create a new role for access to program reports.

@edx/masters-devs

2019-12-11 21:15 UTC, schenedx reviewed
See my inline comments

2019-12-11 21:15 UTC, schenedx commented on registrar/apps/core/permissions.py
> +PROGRAM_READ_METADATA = APP_PREFIX + PROGRAM_READ_METADATA_KEY
Why do we need this permission, and don't have an associated role for this? Maybe we need a `ProgramMetadataRole`?

2019-12-11 21:15 UTC, schenedx commented on registrar/apps/core/permissions.py
> +class ProgramRole(object):
This is a poor name for the base role class. How about `ProgramSpecificRoleBase`?

2019-12-12 19:42 UTC, schenedx approved these changes
👍 LGTM. Good work

2019-12-12 19:42 UTC, schenedx commented on registrar/apps/core/permissions.py
> +# A user with this permission can read any metadata about an program.
#NIT `about a program`

2019-12-12 21:01 UTC, merged

2019-12-12 21:03 UTC, zacharis278 requested changes

2019-12-12 21:03 UTC, Zacharis278 commented on registrar/apps/core/permissions.py
> +class ProgramSpecificRoleBase(object):
Do we need to make this specific to program?  Since we want to the ability grant access to reports at the organization level as well we would also need a duplicate of this ReadReportsRole that works with an OrgGroup.  I'm thinking the base class for our roles can just be made generic to avoid this altogether.