Refactor role base to accomodate both org and program
openedx-unsupported/registrar pull request #222
Opened 2019-12-12 21:37 UTC by how015

MST-50
Refactor OrganazitionRole to make it work with both organization and program

@edx/masters-devs

2019-12-13 16:40 UTC, kdmccormick requested changes
Going to request changes on a higher level here.

There shouldn't be a distinction between `ORGANIZATION_`-level and `PROGRAM_`-level permissions. I thought the reason we `Program` to `core` was so that we wouldn't have to make that distinction.

Permissions should be:
* `READ_METADATA`
* `READ_ENROLLMENTS`
* `WRITE_ENROLLMENTS`
* `READ_REPORTS`

Then, by being assigned to specific `Organizations` and `Programs` those permissions are give org- or program-level context.

cc'ing @Zacharis278 @MichaelRoytman in case they have a different take on this.

2019-12-13 20:33 UTC, Zacharis278 commented
@kdmccormick agreed, we chatted about this offline.  The goal is to remove the specific model context from these permissions.  They should match what you have listed here.

2019-12-16 15:38 UTC, schenedx approved these changes
👍

2019-12-16 15:58 UTC, zacharis278 approved these changes
:shipit:

2019-12-16 17:23 UTC, kdmccormick requested changes
Comments that we talked about. Great refactoring though!

2019-12-16 17:23 UTC, kdmccormick commented on registrar/apps/core/models.py
> +            (perms.READ_METADATA_KEY, 'View Organization Metadata'),
`'View Metadata'`

2019-12-16 17:23 UTC, kdmccormick commented on registrar/apps/core/permissions.py
> +READ_REPORTS_KEY = 'read_reports'
As @Zacharis278 @how015 and I talked about offline, we unfortunately need to keep the old codenames (with the `organization_`) prefix for now. Otherwise, everybody who had the `organization_*` permissions would lose them when this PR was deployed.

2019-12-16 17:23 UTC, kdmccormick commented on registrar/apps/core/permissions.py
> +    name = 'read_metadata'
Similarly, this `name` needs to stay prefixed with `organization_`. But the class name and all the other refactors are still good.

2019-12-16 17:23 UTC, kdmccormick commented on registrar/apps/core/migrations/0007_auto_20191216_1518.py
> +# -*- coding: utf-8 -*-
(per the other changes, remove this and roll back locally)

2019-12-16 21:15 UTC, merged