Add ProgramOrgGroup
openedx-unsupported/registrar pull request #228
Opened 2019-12-18 20:32 UTC by how015

MST-60

Create a ProgramOrgGroup model. This model will have a foreign key field to a Program, a foreign key to an Organization, and a role field. The reason we include the Organization in this model is to contextualize the permissions of a program within an organization.

This addresses the problem of a Program A, authored jointly by Organizations 1 and 2. If User X is given program level report access to Program A, they would get access to two nearly identical reports - one for Organization 1 and one for Organization 2, where the two reports differ only in the "authoring organization" column. This avoids this prob

Add sufficient checks/constraints so that a ProgramOrgGroup cannot have an Organization value that isn’t an authoring org of the program

Update permission checking logic to support multiple permission objects (e.g Org or Program)

mixins.py#L80

2020-01-06 16:39 UTC, kdmccormick reviewed
Good work! Some comments here; also, let's chat about the program vs. org role/permission duplication thing.

2020-01-06 16:39 UTC, kdmccormick commented on registrar/apps/api/v1/mixins.py
> +    def _has_permission(self, user, perm, objects):
Nice use of a helper function to simplify code.

Consider naming it `_has_permission_on_any` to clarify that permission on **any** object is sufficient, as opposed to requiring it on **all** objects, which might be assumed by a reader.

Also, you can make it more clear that this function doesn't reference or mutate the `self` object by making it static:
```python
@staticmethod
def _has_permission_on_any(user, perm, objects):
    ...
```

Note that you call static functions in Python with `self.`, just like any other method.

2020-01-06 16:39 UTC, kdmccormick commented on registrar/apps/api/v1/mixins.py
>          Get an object against which required permissions will be checked.
Update the docstring to reflect the new behavior of this method: that it returns a list of objects, for which permission on at least one is required.

2020-01-06 16:39 UTC, kdmccormick commented on registrar/apps/api/v1/mixins.py
I recommend that we return `[]` (empty list) instead of `None` from this method by default.

`[]` makes sense semantically ("there are no objects on which can have permission, so global permissions are required"), and it would allow us to remove the `elif objects:` branch on line 105, because calling `self._has_permission` with an empty list will always return `False`.

2020-01-06 16:39 UTC, kdmccormick commented on registrar/apps/core/permissions.py
> +    ProgramReadMetadataRole
Nit: Prefer trailing commas, as they make diffs nicer and make it easier to add new items to the list.

2020-01-06 16:39 UTC, kdmccormick commented on registrar/apps/core/models.py
> +class ProgramOrgGroup(Group):
Consider naming this `ProgramOrganizationGroup` for the sake of consistency with other classes which spell out the word Organization.

2020-01-06 16:39 UTC, kdmccormick commented on registrar/apps/core/models.py
> +            self._initial_organization = self.program.managing_organization
You can nix the `_initial_organization` member.

It exists on `OrganizationGroup` so that we can un-assign permissions from an org when an org group is changed to a different org.

Because this class operates on Programs, we just need to un-assign permissions from the old program when an instance of it is changed to a different program, which you've already taken care of in the `save` method you wrote. So, there's no need for the `_initial_organization` member.

2020-01-06 16:39 UTC, kdmccormick commented on registrar/apps/core/models.py
> +
The majority of the functions and fields declared in this class are duplicated with those in `OrganizationGroup`.

I recommend doing something like this:
```python

class OrganizationGroupMixin(object):
    # shared fields & methods

class OrganizationGroup(OrganizationGroupMixin, Group):
   # org-specific stuff

class ProgramOrganizationGroup(OrganizationGroupMixin, Group):
   # program-specific stuff
```

2020-01-06 16:39 UTC, kdmccormick commented on registrar/apps/core/permissions.py
> +PROGRAM_READ_METADATA = APP_PREFIX + PROGRAM_READ_METADATA_KEY
I'm a bit confused about why we need a program-read-metadata permission but not any other program-specific permissions. Let's chat.

2020-01-08 18:22 UTC, how015 commented on registrar/apps/core/models.py
> +class ProgramOrgGroup(Group):
will do this in a separate PR because this change requires data migration, I tend to do it safely :)

2020-01-08 18:33 UTC, how015 commented on registrar/apps/core/models.py
> +
will put the refactor work in https://openedx.atlassian.net/browse/MST-87

2020-01-08 18:34 UTC, zacharis278 requested changes
Overall looks great just a lot of little comments.  I do think we need to add several tests to cover the case of having permissions assigned at the ProgramOrgGroup on the models and for each affected endpoint.

2020-01-08 18:34 UTC, zacharis278 commented on codecov.yml
> +  - "registrar/apps/core/models.py"
why do we need to ignore test coverage on this file?

2020-01-08 18:34 UTC, zacharis278 commented on registrar/apps/api/v1/views.py
>          if not user.has_perm(self.permission_filter):
This section of code won't return programs if the user only has the requested permission at the program level.  This needs to check the program object with the appropriate permission as well.  PERMISSION_QUERY_PARAM map would need to be updated to support this.

2020-01-08 18:34 UTC, zacharis278 commented on registrar/apps/api/constants.py
>  ENROLLMENT_PERMISSIONS_LIST = [
I think this should also include the program permissions

2020-01-08 18:34 UTC, zacharis278 commented on registrar/apps/core/permissions.py
> +class APIPermissionBase(object):
nice, I like this solution 👍

2020-01-08 18:34 UTC, zacharis278 commented on registrar/apps/api/mixins.py
> +class CustomEncoder(json.JSONEncoder):
Can you add a docstring explaining what this does?

2020-01-08 18:34 UTC, Zacharis278 commented on registrar/apps/core/models.py
> +    organization = models.ForeignKey(Organization, on_delete=models.CASCADE)
can we change this to something like `granting_organization`.  Hopefully that will it more clear to users using the admin page that Program is the model being assigned a role.

2020-01-08 18:34 UTC, Zacharis278 commented on registrar/apps/core/permissions.py
>  PERMISSIONS = {
if this is just Organization permissions can we refactor the name to make that more clear?

2020-01-08 18:36 UTC, how015 commented on registrar/apps/core/models.py
> +            self._initial_organization = self.program.managing_organization
Agree with you, Kyle, but per MST-60's task description, "The reason we include the Organization in this model is to contextualize the permissions of a program within an organization."

2020-01-08 19:01 UTC, Zacharis278 commented on registrar/apps/core/models.py
> +class ProgramOrgGroup(Group):
If this PR is creating that model in the first place that original migration can be recreated now before committing the model to master.  You'll be much better off doing that because changing model names after the fact is cumbersome due to our blue-green deployments.

2020-01-08 20:50 UTC, how015 commented on registrar/apps/core/models.py
> +    organization = models.ForeignKey(Organization, on_delete=models.CASCADE)
https://openedx.atlassian.net/browse/MST-87 since this will result in data migration.

2020-01-08 20:54 UTC, how015 commented on codecov.yml
> +  - "registrar/apps/core/models.py"
Will address it in https://openedx.atlassian.net/browse/MST-87

2020-01-08 20:57 UTC, kdmccormick commented on registrar/apps/core/permissions.py
> +class APIPermissionBase(object):
I balked at this when you first showed me it, but now that I'm looking at it more closely, I like the look of it. :+1:

2020-01-08 21:31 UTC, how015 commented on registrar/apps/core/models.py
> +class ProgramOrgGroup(Group):
got it, will do it in this diff

2020-01-08 22:26 UTC, how015 commented on registrar/apps/api/v1/views.py
>          if not user.has_perm(self.permission_filter):
right, fixed this logic like below

2020-01-10 18:00 UTC, zacharis278 reviewed
looks good.  Just a few comments on our test coverage

2020-01-10 18:00 UTC, zacharis278 commented on registrar/apps/api/v1/tests/test_views.py
> -    @ddt.data(
don't we still need these test cases?  Additionally it looks like the test_program_filters test doesn't yet cover the case of a user with permissions assigned at the program

2020-01-10 18:00 UTC, zacharis278 commented on registrar/apps/core/tests/test_models.py
do we have any tests for the new ProgramOrganizationGroup model?

2020-01-10 21:12 UTC, zacharis278 approved these changes
I suggest leaving the strings documenting organization permissions (e.g. View organization metadata) alone just to avoid migrating that field and having to manually re-assign those options in prod.

Otherwise LGTM 💃

2020-01-10 21:54 UTC, merged