add pending user group model
openedx-unsupported/registrar pull request #234
Opened 2020-01-14 21:14 UTC by how015

https://openedx.atlassian.net/browse/MST-88

2020-01-16 19:43 UTC, kdmccormick requested changes
I imagine that we want to only end up with one model, right? Otherwise, we may as well just have a `PendingUserProgramGroup`.

Do you have a plan for removing `PendingUserOrganizationGroup`?

Alternatively, is there a way to just rename  `PendingUserOrganizationGroup` to `PendingUserGroup`?

2020-01-17 15:22 UTC, how015 commented
> I imagine that we want to only end up with one model, right? Otherwise, we may as well just have a `PendingUserProgramGroup`.
> 
> Do you have a plan for removing `PendingUserOrganizationGroup`?
> 
> Alternatively, is there a way to just rename `PendingUserOrganizationGroup` to `PendingUserGroup`?

In the UI, Pending User Organization Group is removed and replaced with Pending User Group. 

We keep PendingUserOrganizationGroup just for backward compatibility, i.e. for the existing Pending User Organization Groups, we still want to consume (and then delete) them upon user login.

We will completely remove the model of PendingUserOrganizationGroup once we are sure all PendingUserOrganizationGroup instances are deleted.

2020-01-21 16:33 UTC, zacharis278 approved these changes

2020-01-21 16:33 UTC, zacharis278 commented on registrar/apps/core/signals.py
> +    For backward compatibility, if an old pending user organization group record exists,
maybe explain a bit what backwards compatibility means here.  e.g. we have existing production records yet to be consumed, but no new records will be created.  May also be worth updating the docstring on PendingOrganizationGroup as well to point out the planned deprecation.

2020-01-21 20:50 UTC, kdmccormick requested changes
Thanks for thinking of the migration process. It sounds good to me.

I requested some more changes, but they are fairly minor, and this should be good to go soon.

2020-01-21 20:50 UTC, kdmccormick commented on registrar/apps/core/models.py
> +            )
Think about what would happen in this method if we assigned `group` to a generic `Group`.

2020-01-21 20:50 UTC, kdmccormick commented on registrar/apps/core/signals.py
> +            'add group {} into user group for user {}'.format(
let's clear up this phrasing: `'add user {} to group {}'`

2020-01-21 20:50 UTC, kdmccormick commented on registrar/apps/core/tests/factories.py
> +        model = PendingUserOrganizationGroup
why not switch this over to `PendingUserGroup` too?

2020-01-22 19:58 UTC, schenedx reviewed
Basically tagging onto what Kyle provided as feedbacks. This is close. Thank you for the refactoring

2020-01-22 19:58 UTC, schenedx commented on registrar/apps/core/tests/test_models.py
> +    def test_pending_program_group_string(self):
Please add an unit test case for a pending user group that links to a group that do not link to either Program nor Organization. Basically, test the case when the Group is standing alone.

2020-01-23 21:00 UTC, kdmccormick commented on registrar/apps/core/models.py
> +        )
I'd include `role` too, just like the others do.

2020-01-23 21:12 UTC, how015 commented on registrar/apps/core/tests/factories.py
> +        model = PendingUserOrganizationGroup
This is there to test backward compatibility.

2020-01-23 21:13 UTC, merged