Program course listing
openedx-unsupported/registrar pull request #26
Opened 2019-03-12 19:23 UTC by Zacharis278

### [EDUCATOR-4092](https://openedx.atlassian.net/browse/EDUCATOR-4092)

2019-03-13 16:40 UTC, kdmccormick requested changes
Good work, just a few comments.

2019-03-13 16:40 UTC, kdmccormick commented on registrar/apps/api/serializers.py
> +    key = serializers.CharField()
Please base these fields names off of [the API spec](https://docs.google.com/document/d/1x3nIpJ16KJelS-OoTxZZgyRAyoBXH6EKVxhH-C6SEgw/edit?ts=5c892a27#heading=h.t83iv1vesc0v). The field names on the underlying object can be specified with `source`

2019-03-13 16:40 UTC, kdmccormick commented on registrar/apps/api/v1/views.py
> +        course_runs = []
Might be good to drop an inline comment here saying something to the effect of "we do not support old-style programs, and we do not go more than one level deep in the program/curricula tree when looking for course runs"

2019-03-13 16:40 UTC, kdmccormick commented on registrar/apps/enrollments/data.py
> +def _get_request(url, client=None):
With this change we will be re-authenticating with every request. Not saying that's necessarily a bad thing, but I'm wondering why you decided to make this change.

2019-03-13 17:34 UTC, Zacharis278 commented on registrar/apps/api/serializers.py
> +    key = serializers.CharField()
ahh good call I'll translate the output values

2019-03-13 17:36 UTC, Zacharis278 commented on registrar/apps/enrollments/data.py
> +def _get_request(url, client=None):
Generally, yes.  We aren't managing a long-term session, this appears to be the model we're using for backend requests elsewhere as well.  That optional client param would allow you to re-use a session if you wanted to make multiple backend requests.

2019-03-13 18:07 UTC, iloveagent57 reviewed
Looks pretty good, I just found one typo, looks like you and Kyle have covered everything else.

2019-03-13 18:07 UTC, iloveagent57 commented on registrar/apps/api/v1/views.py
> +        or 404 if now such program exists.
s/now/no/

2019-03-13 21:05 UTC, kdmccormick requested changes
One more comment. Looks good otherwise.

2019-03-13 21:05 UTC, kdmccormick commented on registrar/apps/enrollments/data.py
> +    url = urljoin(settings.DISCOVERY_BASE_URL, 'api/v1/programs/{}/').format(program_uuid)
This will blow up and give a 500 if the program doesn't exist in Discovery. Which is fine... but I think it'd be good to catch the Discovery 404, log an error that Registrar is out of sync with Discovery, and then return a 500.

2019-03-14 14:04 UTC, Zacharis278 commented on registrar/apps/enrollments/data.py
> +    url = urljoin(settings.DISCOVERY_BASE_URL, 'api/v1/programs/{}/').format(program_uuid)
huh, turns out discovery just 500's on this.  Anyway, added a log message in case this happens.

2019-03-14 14:18 UTC, merged