unit test successful write
openedx-unsupported/registrar pull request #290
Opened 2020-04-06 13:55 UTC by how015

## Description

MST-186, for now, only a successful unit test is added, waiting for comments on how to mock waffle flag.
Per https://waffle.readthedocs.io/en/stable/testing/automated.html, looks like we can only make the flag a deterministic value for unit test.

@edx/masters-devs

2020-04-06 14:16 UTC, Zacharis278 commented on registrar/apps/api/v1/tests/test_views.py
> +            with override_flag('enable_course_role_management', active=True):
While this does work, have you tried to create a flag that would be tied to an Organization/Program group?  I think that would more closely reflect the way this will be configured for real.

If that seems too kludgy, I'd recommend using the override_flag decorator just to clean up needing to add a with statement to every test.

2020-04-06 15:11 UTC, how015 commented on registrar/apps/api/v1/tests/test_views.py
> +            with override_flag('enable_course_role_management', active=True):
There are two ways to manage waffle flag per [this page](https://waffle.readthedocs.io/en/stable/usage/cli.html#managing-waffle-data-from-the-command-line): "Aside the Django admin interface, you can use the command line tools to manage all your waffle objects."

Correct me if I am wrong: Since neither Django admin interface or command line can be used in unit test, we can't set up a mock group and then activate the waffle flag on it in unit test. So I think our only option is override_flag?

2020-04-08 00:48 UTC, schenedx reviewed
The code change is looking good.
I think you just need to add more unit test to associate different types of permission groups to the waffle flag and ensure the expected result. I am glad the actual code change is actually minimal on the `mixins.py` file

2020-04-08 00:48 UTC, schenedx commented on registrar/apps/api/v1/mixins.py
> +            if not waffle.flag_is_active(self.request, 'enable_course_role_management'):
Why not do these input validation in the function `self.validate_enrollment_data` instead? Why do it right after it? I know the waffle check only applies if the course_id is present. That can also be checked in the `self.validate_enrollment_data` function, right?

2020-04-08 15:11 UTC, Zacharis278 commented
Nice, the payload for this looks good and matches what LMS will be expecting.  I'd second both of Simon's points on moving the validation and additional testing on groups.

2020-04-09 00:52 UTC, how015 commented on registrar/apps/api/v1/mixins.py
> +            if not waffle.flag_is_active(self.request, 'enable_course_role_management'):
You are right Simon, working on it.

2020-04-09 12:52 UTC, schenedx requested changes
Can you add another unit test making sure if the waffle flag is turned on for 1 program, doing course_staff on another program who did not get associated with the waffle flag would return 403?
Could you also please fix your pep8 failure? Make sure the command `make quality` passes before you push your code?

2020-04-09 15:33 UTC, kdmccormick reviewed
Nice job. It looks like Simon and Zach have mentioned everything else that I would have other than two minor comments.

2020-04-09 15:33 UTC, kdmccormick commented on registrar/apps/api/v1/mixins.py
> +                if not isinstance(enrollment.get('course_staff'), bool):
```suggestion
            course_staff_flag = enrollment.get('course_staff')
            if course_id and course_staff_flag is not None:
                if not isinstance(course_staff_flag, bool):
```
Style nit: avoid local code duplication

2020-04-09 15:33 UTC, kdmccormick commented on registrar/apps/api/v1/mixins.py
> +        enrollments = request.data
Why do we need to pass in the whole request?

2020-04-09 19:58 UTC, schenedx approved these changes
I think the code LGTM. Please address Kyle's NIT. Thank you!

2020-04-09 19:58 UTC, schenedx commented on registrar/apps/api/v1/mixins.py
> +        enrollments = request.data
This is because the waffle flag check requires the whole request. See line 334

2020-04-09 21:16 UTC, merged