Add a unit test for feedback
openedx-unsupported/registrar pull request #298
Opened 2020-04-15 02:22 UTC by how015

## Description

TODO: Include a detailed description of the changes in the body of the PR

2020-04-15 13:30 UTC, kdmccormick requested changes
From the ticket:

>    The GET course enrollments endpoint should return an additional body field course_staff
>    The value should match that returned from LMS

These tests catch that :+1: 

> If role management waffle not enabled for the requesting user the course_staff field should not be returned

How about this, though?

2020-04-15 13:31 UTC, schenedx requested changes
The test setup looks good. I think you just need to incorporate the waffle flag.

2020-04-15 13:31 UTC, schenedx commented on registrar/apps/api/v1/tests/test_views.py
> +    def test_ok_with_course_staff(self, format_param, expected_format, expected_contents, _enrollments_mock):
So, the only thing about this test is that, it does not test the waffle flag on or off.
With waffle flag off, even if the LMS API returns a json with course_staff key, the registrar should not return that on the CSV or JSON file.
Only with waffle flag on, the course_staff key and value should show on the registrar output file. Please incorporate your test with waffle flag.

2020-04-15 13:34 UTC, how015 commented on registrar/apps/api/v1/tests/test_views.py
> +    def test_ok_with_course_staff(self, format_param, expected_format, expected_contents, _enrollments_mock):
Got it, thank you, Simon. Actually working on it already :)

2020-04-15 19:55 UTC, schenedx requested changes
See inline comments.

2020-04-15 19:55 UTC, schenedx commented on registrar/apps/api/v1/tests/test_views.py
> +            with activate_waffle_flag('enable_course_role_management', self.stem_admin_group):
If it's waffle disabled, why are you still enabling waffle for a different permission group? That should be a different test case.

2020-04-15 19:55 UTC, schenedx commented on registrar/apps/enrollments/tasks.py
> +        course_role_management_enabled,
Can you please have a default value for this function? It's for deployment backwards compatibility.

2020-04-16 01:18 UTC, schenedx approved these changes
Please fix your quality errors

2020-04-16 01:18 UTC, schenedx commented on registrar/apps/api/v1/tests/test_views.py
> +    def test_ok_course_staff_waffle_enabled_on_other_group(self, format_param, expected_format, expected_contents, _enrollments_mock):
#NIT change the title of this function to `test_no_course_staff_waffle_enabled_on_unrelated_group`

2020-04-16 14:10 UTC, schenedx reviewed
Remember to squash your commits before you merge.

2020-04-16 14:13 UTC, how015 commented
MST-188

2020-04-16 14:14 UTC, merged