Add course_staff field to course enrollment csv upload
openedx-unsupported/registrar pull request #301
Opened 2020-04-23 00:47 UTC by how015

MST-189

2020-04-24 13:36 UTC, schenedx requested changes
Minor comments. This is close.

2020-04-24 13:36 UTC, schenedx commented on registrar/apps/api/v1/tests/test_views.py
> +        expected_enrollments = [{'course_id': 'ac2102fb65', 'status': 'enrolled', 'student_key': '001'},
#NIT This array can be constructed based on the last `enrollments` array.

```suggestion
        expected_enrollments = [enrollment_item.pop('course_staff') for enrollment_item in enrollments]
```

2020-04-24 13:36 UTC, schenedx commented on registrar/apps/api/v1/tests/test_views.py
> +    def test_unmatched_row_data(self):
I say this test needs be executed when the waffle flag is turned on. Please add the waffle flag on patch.

2020-04-24 14:11 UTC, kdmccormick commented on registrar/apps/api/v1/tests/test_views.py
> +        expected_enrollments = [{'course_id': 'ac2102fb65', 'status': 'enrolled', 'student_key': '001'},
Won't that modify the items in `enrollments`?

2020-04-24 14:25 UTC, Zacharis278 commented on registrar/apps/api/v1/views.py
> +        if isinstance(self, CourseRunEnrollmentUploadView):
Instead of needing to typecheck against the class could we do something more like `if self.get_field_names`?

2020-04-24 14:27 UTC, schenedx commented on registrar/apps/api/v1/tests/test_views.py
> +        expected_enrollments = [{'course_id': 'ac2102fb65', 'status': 'enrolled', 'student_key': '001'},
@kdmccormick Huh, I didn't realize that. But I think we can do copy then?
Frankly, I am also fine leaving this as it is.

2020-04-24 14:32 UTC, kdmccormick commented on registrar/apps/api/v1/tests/test_views.py
> +        expected_enrollments = [{'course_id': 'ac2102fb65', 'status': 'enrolled', 'student_key': '001'},
As-is strikes me as fine. Sometimes I like when tests have their data fully spelled-out instead of created by Python logic. The latter can obscure what the test is doing and hide bugs.

2020-04-24 21:01 UTC, michaelroytman commented on registrar/apps/api/v1/views.py
> +        if isinstance(self, CourseRunEnrollmentUploadView):
I think that would get you an `AttributeError` if `get_field_names` is not defined on the class. I think the following would work.

```
get_field_names = getattr(self, 'get_field_names', None)
if get_field_names:
    self.field_names = get_field_names(request)
```

2020-04-24 21:01 UTC, MichaelRoytman commented on registrar/apps/api/v1/views.py
> +        if isinstance(self, CourseRunEnrollmentUploadView):
That said, there's something about this that makes me uncomfortable. I don't like that the parent class `EnrollmentUploadView` knows about its child class `CourseRunEnrollmentUploadView`. I think that the original intent of the shared `field_names` field no longer applies here because of the necessary change to `CourseRunEnrollmentUploadView`.

A thing that could be better is to define a method `get_field_names(request)` that each subclass would implement and the `post` method could call without needing to worry about type of the subclass. I realize that the `request` argument would go unused in all but the `CourseRunEnrollmentUploadView` case, though. I'm still thinking about this a bit, but I wanted to get my thoughts on the page.

2020-04-29 18:08 UTC, MichaelRoytman commented on registrar/apps/api/v1/views.py
> +        if isinstance(self, CourseRunEnrollmentUploadView):
I just wanted to follow up on this with some additional thoughts; credit to Cale for explaining this approach to me.

I think a good pattern to follow for something like this is the following.

Implement a base implementation of `get_field_names` on the base class.

This default implementation will return `self.fieldnames`, if it exists on the class. If it doesn't, throw an exception or do whatever is appropriate.

Classes that are able to statically define the fieldnames they care about, like `ProgramEnrollmentUploadView`, will do so.

Classes that are unable to statically define the fieldnames they care about, like `CourseRunEnrollmentUploadView`, will overwrite the implementation of `get_fieldnames` to do what it is they need.

And example of this kind of approach can be found in Django's [get_queryset].(https://docs.djangoproject.com/en/3.0/ref/class-based-views/mixins-single-object/#django.views.generic.detail.SingleObjectMixin.get_queryset) method.

2020-05-01 16:25 UTC, Zacharis278 commented on registrar/apps/api/v1/tests/test_views.py
> +    def build_enrollment(self, status, student_key=None, course_staff='', course_id=None):
this is basically the exact same function as CourseEnrollmentUploadTest.build_enrollment with an extra parameter.  I think we can just add an optional course staff there to avoid repeating code.

2020-05-01 16:35 UTC, Zacharis278 commented on registrar/apps/enrollments/tests/test_tasks.py
> +    def test_success_status_course_staff_included(self, any_successes, any_failures, expected_code_str):
IMO re-testing the status codes here is redundant.  I think we only need one successful run of this to validate the course_staff inclusion.

A gap here is that `mock_write_enrollments` doesn't do anything with the passed in `course_staff` value so we aren't really validating that it is included in the JSON payload sent to LMS.  One way to handle this is using `assert_called_with` on the mock object.  See https://docs.python.org/3/library/unittest.mock.html

2020-05-02 15:15 UTC, schenedx reviewed
Don't really have other comments besides what Zach has commented. This is definitely more complicated than originally thought. Good job for all those tests and making sure all your test cases are covered.

2020-05-02 15:15 UTC, schenedx commented on registrar/apps/core/tests/test_utils.py
> +    csv_with_null = csv_fmt.format(pepper_is_vegetarian='')  # Empty value
#NIT Better variable name for this is `csv_with_empty`

2020-05-04 13:05 UTC, how015 commented on registrar/apps/api/v1/tests/test_views.py
> +    def build_enrollment(self, status, student_key=None, course_staff='', course_id=None):
csv_headers is the reason why I create the new class because csv_headers is also referenced in the parent class of EnrollmentUploadMixin and therefore we can't define two different csv_headers in the same class

2020-05-04 13:49 UTC, Zacharis278 commented on registrar/apps/api/v1/tests/test_views.py
> +    def build_enrollment(self, status, student_key=None, course_staff='', course_id=None):
I think a simple way to solve that would be to use a getter for CSV headers instead of a static value similar to what we did with the view classes.  e.g. `def get_csv_headers(course_staff_enabled=False):`

2020-05-04 18:15 UTC, how015 commented on registrar/apps/api/v1/views.py
> +        enrollments = load_records_from_uploaded_csv(csv_file, self.get_field_names(request), self.optional_fields)
optional_fields=frozenset()

OR

optional_fields=None
(and then in the function)
optional_fields = optional_fields or set()

2020-05-04 18:16 UTC, how015 commented on registrar/apps/core/utils.py
> +def load_records_from_uploaded_csv(csv_file, field_names, optional_fields=set()):
optional_fields=frozenset()

OR

optional_fields=None
(and then in the function)
optional_fields = optional_fields or set()

2020-05-04 18:16 UTC, kdmccormick commented on registrar/apps/core/utils.py
> +def load_records_from_csv(csv_string, field_names, optional_fields=set()):
```suggestion
def load_records_from_csv(csv_string, field_names, optional_fields=frozenset()):
```

2020-05-04 18:17 UTC, kdmccormick commented on registrar/apps/core/utils.py
> +def load_records_from_uploaded_csv(csv_file, field_names, optional_fields=set()):
```suggestion
def load_records_from_uploaded_csv(csv_file, field_names, optional_fields=frozenset()):
```

2020-05-04 18:18 UTC, kdmccormick commented on registrar/apps/core/utils.py
> +    required_fields = field_names - set(optional_fields)
(ALTERNATIVE SOLUTION)

If using `frozenset` doesn't work...

Do `def load_records_from_csv(csv_string, field_names, optional_fields=None):` in the function signatures,
and then here, do:
```suggestion
    required_fields = field_names - (optional_fields or set())
```

2020-05-04 21:31 UTC, how015 commented on registrar/apps/api/v1/tests/test_views.py
> +    def build_enrollment(self, status, student_key=None, course_staff='', course_id=None):
@Zacharis278 would sync with you further on this, tend to think make it separate class may be more adequate.

2020-05-04 21:48 UTC, how015 commented on registrar/apps/api/v1/tests/test_views.py
> +    def build_enrollment(self, status, student_key=None, course_staff='', course_id=None):
CourseEnrollmentUploadCourseStaffTest and CourseEnrollmentUploadTest will run the basic tests from EnrollmentUploadMixin with their own csv_headers.

2020-05-05 14:53 UTC, matthugs reviewed
(would approve but don't want to do that while travis is not passing)

2020-05-05 14:53 UTC, matthugs commented on registrar/apps/api/v1/views.py
> +        if waffle.flag_is_active(request, 'enable_course_role_management'):
How long will we need this waffle flag? Do we have a ticket in JIRA tracking when it can be removed, assuming it's a temporary stage of a roll-out plan? If so, please include a comment referencing that ticket, and include details in the ticket about what needs to be true before this waffle flag can be removed.

2020-05-05 14:53 UTC, matthugs commented on registrar/apps/enrollments/tests/test_tasks.py
> +    def mock_write_enrollments(self, any_successes, any_failures, expected_enrolls_by_course_key=()):
it looks like code underneath this assumes that `expected_enrolls_by_course_key` is a dict

2020-05-05 15:16 UTC, kdmccormick commented on registrar/apps/enrollments/tests/test_tasks.py
> +    def mock_write_enrollments(self, any_successes, any_failures, expected_enrolls_by_course_key=()):
@how015 If setting the default param value to `{}` gives you a "dangerous default value" Pylint warning, then I suggest setting it to `None`. Then, in the body of the function, you can write:
```python
expected_enrolls_by_course_key = expected_enrolls_by_course_key or {}
```

2020-05-05 20:04 UTC, how015 commented on registrar/apps/api/v1/views.py
> +        if waffle.flag_is_active(request, 'enable_course_role_management'):
MST-190 is the ticket

2020-05-05 21:01 UTC, matthugs commented on registrar/apps/api/v1/views.py
> +        if waffle.flag_is_active(request, 'enable_course_role_management'):
Could you include that ticket number in a line comment above the waffle flag check?

2020-05-05 21:03 UTC, matthugs approved these changes

2020-05-06 12:41 UTC, merged