add name and email to getProgramEnrollment response
openedx-unsupported/registrar pull request #315
Opened 2020-06-10 16:31 UTC by how015

MST-234

2020-06-16 15:22 UTC, schenedx requested changes
Requesting variable name changes. Rest looks good so far.

2020-06-16 15:22 UTC, schenedx commented on registrar/apps/api/v1/tests/test_views.py
> +    new_enrollments = [
Instead of `new_enrollments`. I think a better variable name is `user_linked_enrollments`. The same name pattern can apply to the CSV and JSON as well.

2020-06-16 15:22 UTC, schenedx commented on registrar/apps/api/v1/tests/test_views.py
> +    def test_new_ok(self, format_param, expected_format, expected_contents, _enrollments_mock):
Better name for `test_new_ok` is `test_enrollments_with_user_info_ok`

2020-06-16 15:22 UTC, schenedx commented on registrar/apps/enrollments/serializers.py
> +class NewProgramEnrollmentSerializer(ProgramEnrollmentSerializer):
Really don't like the serializer name. How about `ProgramEnrollmentWithUsernameEmailSerializer`?

2020-06-16 15:22 UTC, schenedx commented on registrar/apps/enrollments/serializers.py
> +    New serializer for program enrollment API response.
Please update this comment so it reflects the username and email addition

2020-06-17 11:03 UTC, schenedx commented on registrar/apps/api/v1/tests/test_views.py
> +    @mock.patch.object(lms, 'get_program_enrollments', return_value=user_linked_enrollments)
Instead of mock patching `get_program_enrollments`, you can patch the function 1 step further by patching `get_all_paginated_results` function. This way, you can test your changes in the function `get_program_enrollments`. And you won't need those `#progma` coverage ignores.

2020-06-18 13:50 UTC, kdmccormick approved these changes
Nice work! Other than a couple comments, this LGTM.

2020-06-18 13:50 UTC, kdmccormick commented on registrar/apps/api/v1/views.py
> +            list_program_enrollments, self.program.key, include_username_email)
```suggestion
        return self.invoke_download_job(
            list_program_enrollments, self.program.key, include_username_email
        )
```
Style nit based on [our Python style guide](https://edx.readthedocs.io/projects/edx-developer-guide/en/latest/style_guides/python-guidelines.html#breaking-long-lines).

2020-06-18 13:50 UTC, kdmccormick commented on registrar/apps/enrollments/tasks.py
> +        serialized = json.dumps(enrollments, indent=4, sort_keys=True)
There are two other `json.dumps` calls in this file. For consistency, I recommend adding `sort_keys=True` to them as well.

2020-06-18 14:15 UTC, schenedx approved these changes
👍 Kyle's feedback are nice to address, but not blocking

2020-06-18 14:23 UTC, merged