WIP Add the PendingOrganizationUserRole model to enable the auto role assignment
openedx-unsupported/registrar pull request #33
Opened 2019-03-18 12:41 UTC by schenedx

## Description

This is still an WIP

This is the PR to add the PendingOrganizationUserRole so we can pre-assign user role before the user is created in core.

2019-03-19 18:06 UTC, iloveagent57 reviewed
I think the missing underscore is what's throwing off the pii checker.

2019-03-19 18:06 UTC, iloveagent57 commented on registrar/apps/core/signals.py
> +    user_instance = kwargs.get("instance", None)
Nit: `None` is already the default returned by `dict.get()` when the item doesn't exist.

2019-03-19 18:06 UTC, iloveagent57 commented on registrar/apps/core/signals.py
> +        logger.info('User is null when we handle the user save signal!')
I'd argue that this is actually an error.

2019-03-19 18:06 UTC, iloveagent57 commented on registrar/apps/core/signals.py
> +    If there are pending organization user role exists, assign the user the new OrganizationGroup
"If a pending user organization group record exists, add the user to the OrganizationGroup and delete the pending record."

2019-03-19 18:06 UTC, iloveagent57 commented on registrar/apps/core/models.py
> +    .. pii_types: email address
Ohh, try changing this to `email_address` (notice the underscore)

2019-03-19 18:28 UTC, schenedx commented on registrar/apps/core/signals.py
> +    user_instance = kwargs.get("instance", None)
Good point. Simplified

2019-03-19 18:28 UTC, schenedx commented on registrar/apps/core/signals.py
> +        logger.info('User is null when we handle the user save signal!')
changed to `logger.error`

2019-03-19 18:28 UTC, schenedx commented on registrar/apps/core/signals.py
> +    If there are pending organization user role exists, assign the user the new OrganizationGroup
Updated

2019-03-19 18:29 UTC, schenedx commented on registrar/apps/core/models.py
> +    .. pii_types: email address
Thank you

2019-03-19 18:33 UTC, iloveagent57 approved these changes

2019-03-19 18:43 UTC, kdmccormick commented
I realized #32 breaks the admin panel for adding `OrganizationGroups`. I fix it in #34. Nothing for you to do here other than rebase this once #34 merges, which will hopefully be in a moment.

2019-03-19 19:04 UTC, kdmccormick requested changes

2019-03-19 19:04 UTC, kdmccormick commented on registrar/apps/core/models.py
> +    unique_together = ('user_email', 'organization_group')
This should be within `Meta`

2019-03-19 19:04 UTC, kdmccormick commented on registrar/apps/core/permissions.py
> +ROLE_CHOICES = (
Please remove this; I think this was an artifact from rebasing. `ROLE_CHOICES` is now defined dynamically within `OrganizationGroup`.

2019-03-20 13:22 UTC, schenedx commented on registrar/apps/core/models.py
> +    unique_together = ('user_email', 'organization_group')
This is done

2019-03-20 13:22 UTC, schenedx commented on registrar/apps/core/permissions.py
> +ROLE_CHOICES = (
Thank you. I forgot about the removal here.

2019-03-20 13:53 UTC, kdmccormick approved these changes
LGTM :+1:

2019-03-20 13:54 UTC, merged