Add v3 endpoint for program list pagination
openedx-unsupported/registrar pull request #356
Opened 2020-09-08 20:06 UTC by alangsto

## [MST-383](https://openedx.atlassian.net/browse/MST-383)

Added new v3 endpoint to allow users to specify a page number and page size as a query parameter. If no page number or size are specified, there is a default page number of 1 and size of 10.

2020-09-08 20:09 UTC, alangsto commented on registrar/apps/api/v3/tests/test_views.py
> +    def test_valid_pagination(self):
New pagination tests start here

2020-09-09 14:45 UTC, schenedx requested changes
I am not sure why you need the customized paginator.

2020-09-09 14:45 UTC, schenedx commented on registrar/apps/api/v3/pagination.py
> +        return Response({
Why do you need the customization on the PageNumberPagination this way?
Why do we need `next` and `previous` wrapped in another level?

2020-09-09 14:45 UTC, schenedx commented on registrar/apps/api/v3/tests/test_views.py
> +class ProgramListViewTests(RegistrarAPITestCase, AuthRequestMixin):
Instead of copy and paste the tests here, can't you do refactoring on the original ProgramListViewTests, then inherit those test here?

2020-09-09 14:45 UTC, schenedx commented on registrar/apps/api/v3/views.py
> +@schema_for(
Nice. I like how you are using the new doc system now.

2020-09-09 15:10 UTC, alangsto commented on registrar/apps/api/v3/pagination.py
> +        return Response({
I agree with your comment that customization can always be added later if necessary, so I removed the custom response.

2020-09-09 15:11 UTC, alangsto commented on registrar/apps/api/v3/tests/test_views.py
> +class ProgramListViewTests(RegistrarAPITestCase, AuthRequestMixin):
I wasn't quite sure of a good way to refactor and inherit because the response format of this endpoint is different. All of the V1 endpoints look at response.data, but in V3 they need to look at response.data.results

2020-09-09 15:14 UTC, schenedx commented on registrar/apps/api/v3/tests/test_views.py
> +class ProgramListViewTests(RegistrarAPITestCase, AuthRequestMixin):
Yep, you can override the function `assert_tracking` to help with that I believe.

2020-09-09 15:17 UTC, alangsto commented on registrar/apps/api/v3/tests/test_views.py
> +class ProgramListViewTests(RegistrarAPITestCase, AuthRequestMixin):
I could definitely inherit the RegistrarAPITestCase class so I will update the code to include that.

2020-09-09 18:03 UTC, alangsto commented on registrar/apps/api/v3/tests/test_views.py
> +class ProgramListViewTests(RegistrarAPITestCase, AuthRequestMixin):
@schenedx I've tried to use inheritance for reusing tests, but I'm running into some problems (current code is up to date and reflects these issues). The problem that I'm running into is that by using inheritance, the tests are each called twice. This is causing issues with the build. 

I've found that adding `__test__=False` to the class being inherited fixes the issue of tests being called twice, but that inherited class should be tested normally (for v1 tests). Adding `__test__=False` prevents this normal behavior.

My next thought is to add a base test class which can be inherited for both the v1 and v3 tests, because then `__test__=False` can be added. However, when this is added, ddt.data is ignored in the base test class, and then it would need to be added to both the v1 and v3 test class again. This option seems more complicated than I would have liked, especially because it includes rewriting the v1 testing class, so I feel like copying may be the best option.

Let me know if I was off base with how I was using inheritance, maybe there's something I'm missing

2020-09-09 18:23 UTC, alangsto commented on registrar/apps/api/v3/tests/test_views.py
> +class ProgramListViewTests(RegistrarAPITestCase, AuthRequestMixin):
@schenedx Just wanted to note that for reusability purposes, adding a base test class is the best option, I just wasn't sure if that would be refactoring the code too much

2020-09-09 19:30 UTC, alangsto commented
@schenedx thanks for the feedback! I removed the v1 tests.

2020-09-09 19:35 UTC, schenedx approved these changes
👍

2020-09-09 19:44 UTC, merged