add segment to registrar
openedx-unsupported/registrar pull request #39
Opened 2019-03-19 18:47 UTC by jansenk

basic setup for segment.io integration with registrar

2019-03-19 19:38 UTC, schenedx requested changes
Mostly looks good. Let me know if you have feedback

2019-03-19 19:38 UTC, schenedx commented on registrar/apps/api/__init__.py
> +default_app_config = 'registrar.apps.api.apps.ApiConfig'
According to latest django documentation at https://docs.djangoproject.com/en/2.1/ref/applications/#configuring-applications (see paragraph 5), you should not have the changes in here to incorporate a new app config.

2019-03-19 19:38 UTC, schenedx commented on registrar/settings/base.py
> +SEGMENT_KEY = "replace-me"
new line please

2019-03-19 19:38 UTC, schenedx commented on registrar/apps/api/apps.py
> +            analytics.write_key = settings.SEGMENT_KEY
Are you sure the `settings.SEGMENT_KEY` won't be None? Should we handle the `None` case

2019-03-19 21:35 UTC, jansenk commented on registrar/apps/api/__init__.py
> +default_app_config = 'registrar.apps.api.apps.ApiConfig'
hmm, okay. I was following the segment django documentation.
https://segment.com/docs/sources/server/python/#django

2019-03-20 17:06 UTC, schenedx approved these changes
👍

2019-03-20 17:12 UTC, iloveagent57 approved these changes
That looks right to me 👍

2019-03-20 17:52 UTC, merged