chore: remove constraints related to db integrity errors
openedx-unsupported/registrar pull request #464
Opened 2022-03-15 13:58 UTC by schenedx

## Description
Remove the constraints on `moto` and `idna` because these can be address by unit test code changes.

2022-03-15 14:28 UTC, matthugs requested changes
Do we need `moto` outside of the test requirements? I wonder if we can just eliminate it from a number of requirements files (except for test) while we're looking at this?

2022-03-15 14:28 UTC, matthugs commented on requirements/common_constraints.txt
> +
it looks like this comment is getting duplicatively added every time we run, e.g. `make upgrade`? We should maybe report that to BOM so they can help us avoid needing to think about it, and remove this from our diffs.

2022-03-15 14:35 UTC, schenedx commented
@matthugs the `moto` library is only specified in the `test.in` file. However, `local.in`, `devstack.in` and `monitoring/requirements.in` all import `test.in`. That's why moto is installed on those. I don't want to expand the scope of this change to tease out requirements list dependencies.

2022-03-15 14:37 UTC, schenedx commented on requirements/common_constraints.txt
> +
Removed the duplicates from the PR. I'll investigate why `make upgrade` dupes this. That should be outside the scope of this PR tho.

2022-03-16 14:52 UTC, alangsto approved these changes
👍

2022-03-16 15:07 UTC, merged