patch course enrollments
openedx-unsupported/registrar pull request #54
Opened 2019-03-26 17:46 UTC by jansenk

pointing at my previous branch for the sake of the diff

added an optional dict argument to validate_and_echo_statuses to allow us to return enrolled-processing as a status since enrolled is not a valid status to return from this endpoint

2019-03-26 21:16 UTC, kdmccormick requested changes

2019-03-26 21:16 UTC, kdmccormick commented on registrar/apps/api/v0/views.py
> +        status_replacements = {'enrolled': 'enrolled-processing'}
`enrolled-waiting`, per the spec

(although that's subject to change soon anyway)

2019-03-26 21:16 UTC, kdmccormick commented on registrar/apps/api/v0/views.py
> +    def validate_and_echo_statuses(self, request, status_replacements=None):
`status_replacements={}` would remove the requirement of checking `if status_replacements`

2019-03-26 21:16 UTC, kdmccormick commented on registrar/apps/api/v0/views.py
>      """ Provides the validate_and_echo_statuses function """
Can you add a note here that says that subclasses of `EchoStatusesMixin` must implement `get_serializer_class`?

2019-03-26 21:16 UTC, kdmccormick commented on registrar/apps/api/v0/views.py
>      def get_serializer_class(self):
Something I realized when working on my own PR: If we make the enrollment views subclass `GenericAPIView` instead of `APIView`, Swagger will call the `get_serializer_class` and the JSON input field in the Swagger UI will start working again.

2019-03-26 22:25 UTC, jansenk commented on registrar/apps/api/v0/views.py
> +    def validate_and_echo_statuses(self, request, status_replacements=None):
That’s causes a pylint warning and I don’t think this little block is too bad

2019-03-27 14:03 UTC, jansenk commented on registrar/apps/api/v0/views.py
> +        status_replacements = {'enrolled': 'enrolled-processing'}
enrolled-processing is in the spec too:
![Screen Shot 2019-03-27 at 10 03 06 AM](https://user-images.githubusercontent.com/1639231/55082196-9608cc00-5077-11e9-8f82-6609ed245a71.png)

2019-03-27 14:15 UTC, kdmccormick commented on registrar/apps/api/v0/views.py
> +    def validate_and_echo_statuses(self, request, status_replacements=None):
Gotcha, no biggie

2019-03-27 14:17 UTC, kdmccormick commented on registrar/apps/api/v0/views.py
> +        status_replacements = {'enrolled': 'enrolled-processing'}
Ah. It was removed from POST at Simon's request but I must have forgotten to remove it from PATCH. My b. Sorry about all these discrepancies in the spec.

2019-03-27 14:23 UTC, jansenk commented on registrar/apps/api/v0/views.py
> +        status_replacements = {'enrolled': 'enrolled-processing'}
as per conversation i removed this stuff and am just echoing 'enrolled' again

2019-03-27 14:31 UTC, schenedx approved these changes
👍

2019-03-27 16:00 UTC, merged