WIP Implement V1 program enrollment GET
openedx-unsupported/registrar pull request #66
Opened 2019-04-16 15:23 UTC by kdmccormick

_This is a work-in-progress_

@edx/masters-neem

2019-04-23 18:55 UTC, schenedx reviewed
See my inline comments. The logic looks mostly good.
1. Please fill out all the TODOs
2. What is your plan to manually test? How to ensure this works on both local machine, and when it deploys to stage, it would work there?
3. What if the request on LMS return 404 or unsuccessful, what would the job status be, failed?

2019-04-23 18:55 UTC, schenedx commented on registrar/apps/api/serializers.py
> +    program_key = serializers.SlugField(source='key')
Why we use Slugfield here instead of the charfield we have specified in Model?

2019-04-23 18:55 UTC, schenedx commented on registrar/apps/api/serializers.py
> +    Serializer for request to modify a program enrollment in LMS
#NIT I don't think it's necessary to say `in LMS`. What if that changes in the future somehow?

2019-04-23 18:55 UTC, schenedx commented on registrar/apps/api/v1/tests/test_views.py
> +    def test_formats(self, fmt, _mock_get_program_enrollments):
#NIT, instead of `fmt`, it is clearer to just spell it out as `format` or `file_format`

2019-04-23 18:55 UTC, schenedx commented on registrar/apps/core/jobs.py
> +                'Multiple UserTaskArtifacts for job ' +
Can you also put in the message saying something like `We return the first artifact of the job`?
It will be good to log the first artifact URL as well for debugging purpose.

2019-04-23 18:55 UTC, schenedx commented on registrar/apps/core/jobs.py
> +    _assert_in_progress(job_id, task_status)
If we don't catch this exception, what would be the api behavior? Do we throw 500 back to user?

2019-04-23 18:55 UTC, schenedx commented on registrar/apps/enrollments/data.py
> +        return response
I agree with this. We should make the helper function here do one thing only.

2019-04-23 19:21 UTC, kdmccormick commented on registrar/apps/api/serializers.py
> +    program_key = serializers.SlugField(source='key')
Haha, I think it was wishful thinking that we used a `SlugField` on the model. I'll change this back.

2019-04-23 19:22 UTC, kdmccormick commented on registrar/apps/api/serializers.py
> +    Serializer for request to modify a program enrollment in LMS
:+1:

2019-04-23 19:23 UTC, kdmccormick commented on registrar/apps/core/jobs.py
> +    _assert_in_progress(job_id, task_status)
Yes. If the task isn't in progress, that would be an anomalous condition that would warrant a 500, in my opinion.

2019-04-23 19:33 UTC, schenedx commented on registrar/apps/core/jobs.py
> +    _assert_in_progress(job_id, task_status)
Yeah, that make sense. Sounds good.

2019-04-23 19:44 UTC, kdmccormick commented
@schenedx Thanks for the pre-review!

1. Will do.
2. This is a little tricky. Locally, I've just been mocking the LMS API by adding `return <a bunch of JSON>` to `get_program_enrollments`, which isn't great. On stage/prod, I'm not sure how this will work at all without the LMS API. Any suggestions here would be appreciated.
3. Yep, in `list_program_enrollments` we catch all HTTPErrors from the LMS API, log them, and mark the job as Failed.

2019-04-26 14:16 UTC, schenedx requested changes
I think the majority of this is good to go. 
See my inline comments.
I am also totally fine with making the get endpoint NOT resilient against LMS failures. If we have need to make it resilient, we will do so later.
Great work!

2019-04-26 14:16 UTC, schenedx commented on .travis.yml
> +    - "sudo rm -f /etc/boto.cfg"
Why should we delete the `boto.cfg`? What error does this cause?

2019-04-26 14:16 UTC, schenedx commented on api.yaml
> +  name: fmt
#NIT why not just use full `format` word for the query string parameter?

2019-04-26 14:16 UTC, schenedx commented on registrar/apps/api/serializers.py
> +    result = serializers.URLField()
Why is the result field no longer nullable?

2019-04-26 14:16 UTC, schenedx commented on registrar/apps/api/v1/tests/test_views.py
> +    def setUpClass(cls):
Just curious, why did you decide to change the method `setUp` to `setUpClass`?

2019-04-26 14:16 UTC, schenedx commented on registrar/apps/api/v1/tests/test_views.py
> +        cls._s3_mock = moto.mock_s3()
Nice~

2019-04-26 14:16 UTC, schenedx commented on registrar/apps/api/v1/views.py
> +        file_format = request.query_params.get('fmt', 'json')
#NIT why not just use `format`?

2019-04-26 14:16 UTC, schenedx commented on registrar/apps/core/job_results.py
> +""" Utilities for storing the results of jobs. """
The name of this file does not match the class names in this file. Maybe rename the file to `job_storage.py`?

2019-04-26 14:16 UTC, schenedx commented on registrar/apps/core/jobs.py
> +def _assert_in_progress(job_id, task_status):
#NIT I just don't like the word `assert` when it's not related to testing.
How about `job_should_in_progress`

2019-04-26 14:16 UTC, schenedx commented on registrar/settings/test.py
> +DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
Is this needed for `moto` library?

2019-04-26 14:16 UTC, schenedx commented on registrar/apps/core/jobs.py
> +    task_fn.apply_async([job_id, user.id] + list(args), kwargs, task_id=job_id)
Should we think about retry on the job? Or we should off load that to the client?

2019-04-26 14:31 UTC, kdmccormick commented on registrar/apps/api/v1/views.py
> +        file_format = request.query_params.get('fmt', 'json')
Django Rest Framework automatically interprets the `format` parameter in a way inconsistent with what we want to do: https://www.django-rest-framework.org/api-guide/format-suffixes/

We could disable it, allowing us to use `format` instead of `fmt`, but that would disable the DRF `format` parameter across all of Registrar.

Do you have thoughts on whether we should stick with `fmt` or disable DRF's `format` for all Registrar APIs?

2019-04-26 14:31 UTC, kdmccormick commented on registrar/apps/api/v1/views.py
> +        file_format = request.query_params.get('fmt', 'json')
Note: DRF also allows us to _rename_ their builtin `format` parameter.

2019-04-26 14:49 UTC, schenedx commented on registrar/apps/api/v1/views.py
> +        file_format = request.query_params.get('fmt', 'json')
I didn't know that. Knowing what you said, I am fine letting this staying at `fmt`

2019-04-26 14:55 UTC, kdmccormick commented on registrar/apps/api/v1/tests/test_views.py
> +    def setUpClass(cls):
Good question. `setUp` is run once per test, and `seUpClass` is run once per class. None of the records created in `setUp` were being modified within any of the tests, so it made sense to create them once per class instead of once per test . The change sped up test execution noticeably on my computer.

2019-04-26 15:02 UTC, kdmccormick commented on api.yaml
> +  name: fmt
(See other comment)

2019-04-26 15:08 UTC, kdmccormick commented on .travis.yml
> +    - "sudo rm -f /etc/boto.cfg"
When I first pushed this code I got a weird error on Travis CI. This line is a patch, for what seems to be a currently unresolved issue: https://github.com/travis-ci/travis-ci/issues/7940

2019-04-26 15:09 UTC, kdmccormick commented on .travis.yml
> +    - "sudo rm -f /etc/boto.cfg"
You know, I'll add a comment to that line.

2019-04-26 15:10 UTC, kdmccormick commented on registrar/apps/api/serializers.py
> +    result = serializers.URLField()
That's a mistake. Good catch.

2019-04-26 15:17 UTC, kdmccormick commented on registrar/settings/test.py
> +DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
Yup. We need our code to _try_ to use S3, so that Moto is able to mock out those calls. If we use FileSystemStorage, then the Moto mock won't do anything.

2019-04-26 15:18 UTC, kdmccormick commented on registrar/apps/core/jobs.py
> +def _assert_in_progress(job_id, task_status):
Makes sense. How about `_confirm_job_in_progress`? I like to start method names with verbs.

2019-04-26 15:26 UTC, kdmccormick commented on registrar/apps/core/jobs.py
> +    task_fn.apply_async([job_id, user.id] + list(args), kwargs, task_id=job_id)
Hm, the only job failure scenario I see that retrying may fix would be if the LMS was temporarily unresponsive. Is that something that we expect to happen often enough for it to bother partners? If so, we can automatically retry. If not, I think one-try is fine for now (knowing we can change it later).

2019-04-26 16:10 UTC, schenedx commented on registrar/apps/api/v1/tests/test_views.py
> +    def setUpClass(cls):
Ah. Got ya. Cool. I'll keep this in mind.

2019-04-26 16:10 UTC, schenedx commented on registrar/apps/core/jobs.py
> +def _assert_in_progress(job_id, task_status):
Yes. That name sounds good

2019-04-26 16:11 UTC, schenedx commented on registrar/apps/core/jobs.py
> +    task_fn.apply_async([job_id, user.id] + list(args), kwargs, task_id=job_id)
One try is fine now. Let's observe and change later if necessary.

2019-04-26 17:15 UTC, schenedx approved these changes
👍

2019-04-26 19:43 UTC, merged