Add segment tracking for all V1-mock views
openedx-unsupported/registrar pull request #75
Opened 2019-04-25 20:26 UTC by schenedx

## Description

This PR is to make sure all the request to v1-mock views will have segment tracking.

@edx/masters-neem Please review

2019-04-26 14:18 UTC, kdmccormick requested changes
Looking good in general. I have a few stylistic suggestions and a couple functionality questions.

2019-04-26 14:18 UTC, kdmccormick commented on registrar/apps/api/segment.py
> +    property_dict = {
This can be done in fewer lines:
```python
property_dict = kwargs.copy()
property_dict['user_organizations'] = ...
```

2019-04-26 14:18 UTC, kdmccormick commented on registrar/apps/api/segment.py
> +def get_user_organizations(user):
This is a great utility function! I can see it being used other places in the codebase in the future. Maybe `registrar/apps/core/utils.py` would be a good place for it?

2019-04-26 14:18 UTC, kdmccormick commented on registrar/apps/api/v1_mock/tests/test_views.py
> +        properties = {}
One liner: `properties = kwargs.copy()`

2019-04-26 14:18 UTC, kdmccormick commented on registrar/apps/api/v1_mock/tests/test_views.py
> +        if properties.get('user_organizations', None) is None:
More Pythonic: `if 'user_organizations' not in properties:`

2019-04-26 14:18 UTC, kdmccormick commented on registrar/apps/api/v1_mock/tests/test_views.py
> +            permission_failure='no_permission_on_org'
General style nit: trailing commas on these multi-line function calls are recommended in the edX style guide

2019-04-26 14:18 UTC, kdmccormick commented on registrar/apps/api/v1_mock/tests/test_views.py
> +        self.assert_segment_tracking(
General style nit: Lots of these calls can be on one line

2019-04-26 14:18 UTC, kdmccormick commented on registrar/apps/api/v1_mock/views.py
> +import registrar.apps.api.segment as segment
Nit: `from registrar.apps.api import segment` is more consistent with the rest of our code.

2019-04-26 14:18 UTC, kdmccormick commented on registrar/apps/api/v1_mock/views.py
> +        if self.course is None:
I see you moved `if self.course is None: raise Http404()` out of `def course()`, presumably so that we can raise the `segment.track` event even if the course key is wrong.

Is there a reason we'd want to do this for invalid course keys, but not for invalid program keys?

2019-04-26 14:18 UTC, kdmccormick commented on registrar/apps/api/v1_mock/views.py
> +            segment.track(
The `segment.track` calls, while important, take up a lot of space in this module and create a lot of noise. It would be nice if we could factor lots of the common code out into a utility function in a mixin.

For example, every `segment.track` call includes `self.request.user.username`, the name of the event (which always starts with `'registrar.v1_mock.'`, and a call to `get_tracking_properties` with `self.request.user` as the first argument. I could imagine being able to just call `self.segment_track('list_program', permission_failure='no_org_key')`

2019-04-26 14:18 UTC, kdmccormick commented on registrar/apps/api/v1_mock/tests/test_views.py
> +    def assert_segment_tracking(self, user=None, **kwargs):
Nice general test structure :+1:

2019-04-26 14:18 UTC, kdmccormick commented on registrar/apps/api/v1_mock/views.py
>              raise PermissionDenied()
We fire segment events for some 4xx errors, but not for all of them. Should we standardize on firing events for all 403s/422s/etc.?

2019-04-26 14:22 UTC, schenedx commented on registrar/apps/api/v1_mock/tests/test_views.py
> +        if properties.get('user_organizations', None) is None:
Ah, I was doing `if not hasattr(properties, 'user_organizations'):`. Then I realized I was barking at the wrong tree.
Thank you for this suggestion. Make sense.

2019-04-26 14:24 UTC, schenedx commented on registrar/apps/api/v1_mock/views.py
>              raise PermissionDenied()
Yep. We should fire events for these as well. Just a miss on my part.

2019-04-26 14:25 UTC, schenedx commented on registrar/apps/api/v1_mock/views.py
> +        if self.course is None:
We should do this for invalid program as well. Let me check to see how to do that.

2019-04-26 15:46 UTC, kdmccormick commented on registrar/apps/api/v1_mock/views.py
> +        if self.course is None:
One suggestion that would allow you to keep the `raise Http404()`s within `def course()` and `def program()`:

Define on every class a mapping from methods to event names, for example: 
`events = {'PATCH': 'patch_program_enrollments', 'POST': 'post_program_enrollments, 'GET': 'get_program_enrollments'}`.

Then, within `def program()` you could do `segment.track(user, self.events(self.request.method), ...)` right before a 404 is raised.

2019-04-29 18:27 UTC, schenedx commented
@kdmccormick I took in all your suggestions and rebased. Please review again.

2019-04-29 21:31 UTC, kdmccormick requested changes
Great progress; I think this is almost there. However, there are places where multiple events are being emitted.

2019-04-29 21:31 UTC, kdmccormick commented on registrar/apps/api/v1_mock/tests/test_views.py
> +        self.mock_track = self.patcher.start()
This can be rolled into `setUpClass`, and `tearDown` could be `tearDownClass`

2019-04-29 21:31 UTC, kdmccormick commented on registrar/apps/api/v1_mock/views.py
> +class SegmentTrackViewMixin(object):
Nice! When we do the V1 events, let's try to remember to pull this mixin up a package level and use it in both API versions.

2019-04-29 21:31 UTC, kdmccormick commented on registrar/apps/api/v1_mock/views.py
> +        segment.track(
Can this call be done with `self.segment_track`?

2019-04-29 21:31 UTC, kdmccormick commented on registrar/apps/api/v1_mock/tests/test_views.py
> +        self.mock_track.assert_called_with(
Would it be fair to test `assert_called_once_with` instead? I feel like we should only be emitting one of these events per request.

Doing so causes about 30 test failures, all on tests in classes `Mock...EnrollmentTests`. I think that's because the way eventing on `validate_and_echo_statuses` is currently implemented causes multiple events in certain cases.

2019-04-29 21:31 UTC, kdmccormick commented on registrar/apps/api/v1_mock/views.py
> +        self.segment_track(program_key=self.program.key)
This will cause multiple events to be fired if there is a failure (this event and the failure event). I recommend emitting the event from within `validate_and_echo_statuses`.

2019-04-30 12:20 UTC, schenedx commented on registrar/apps/api/v1_mock/tests/test_views.py
> +        self.mock_track = self.patcher.start()
This cannot. I tried. We need to patch each time a test is run. Otherwise I think the call counter in the mock won't reset.

2019-04-30 12:20 UTC, schenedx commented on registrar/apps/api/v1_mock/views.py
> +class SegmentTrackViewMixin(object):
Yes. Exactly what I was thinking too.

2019-04-30 13:03 UTC, schenedx commented
@kdmccormick Took all of your feedback in. Please review again.

2019-04-30 13:39 UTC, kdmccormick commented on registrar/apps/api/v1_mock/tests/test_views.py
> +        self.mock_track = self.patcher.start()
Ah, makes sense. Sounds good.

2019-04-30 14:01 UTC, kdmccormick approved these changes
:+1:

I have one suggestion, but my approval stands whether or not you make this change: It might be good to include `program_key` and `course_key` (if available) in the 403 and 404 events.

2019-04-30 16:22 UTC, schenedx commented
> 👍
> 
> I have one suggestion, but my approval stands whether or not you make this change: It might be good to include `program_key` and `course_key` (if available) in the 403 and 404 events.

Took in your suggestion above. I am going to merge.

2019-04-30 16:24 UTC, merged