PATCH program enrollments
openedx-unsupported/registrar pull request #76
Opened 2019-04-29 17:14 UTC by Zacharis278

### [EDUCATOR-4067](https://openedx.atlassian.net/browse/EDUCATOR-4067)

2019-04-29 18:37 UTC, schenedx requested changes
I think we can make the code change a bit more structured to read better?

2019-04-29 18:37 UTC, schenedx commented on registrar/apps/api/v1/tests/test_views.py
> +class ProgramEnrollmentWriteTests(RegistrarAPITestCase, AuthRequestMixin):
Instead of having both POST and PATCH tested in the same class, I rather seeing two different classes with a common mixin. This way, you don't need to run things twice in a test method all the time.
And you can put a lot of common data in the mixin.

2019-04-29 18:37 UTC, schenedx commented on registrar/apps/api/v1/views.py
> -        response = post_lms_program_enrollment(program_uuid, request.data)
The 3 lines before this and one line after this are exactly the same. Maybe create a common handler to make it DRY?

2019-04-30 14:07 UTC, kdmccormick commented on registrar/apps/enrollments/data.py
> +    if update is True:
`if update`

2019-04-30 14:33 UTC, Zacharis278 commented on registrar/apps/api/v1/tests/test_views.py
> +class ProgramEnrollmentWriteTests(RegistrarAPITestCase, AuthRequestMixin):
I updated this so the tests are parameterized since POST and PATCH tests are exactly the same.  I went with that over a mixin since otherwise all of the actual test definitions would be in the mixin instead.

2019-04-30 20:07 UTC, schenedx approved these changes
👍 LGTM

2019-04-30 20:52 UTC, merged