Include curriculum_uuid with program enrollments
openedx-unsupported/registrar pull request #79
Opened 2019-05-02 20:32 UTC by Zacharis278

### [EDUCATOR-4283](https://openedx.atlassian.net/browse/EDUCATOR-4283)

1. Send curriculum_uuid to LMS when creating or updating program enrollments
2. Added caching of discovery programs
3. Fix POST/PATCH to use base class instead of ddt

2019-05-02 21:02 UTC, kdmccormick commented on registrar/apps/enrollments/data.py
> +        cache.set(PROGRAM_CACHE_KEY_TPL.format(uuid=program_uuid), program)
I know this is still a draft, but heads up: the default cache lifetime is 5 minutes. If you want it to last indefinitely, pass in `None` here, or set the default timeout to `None` in config.

2019-05-02 21:05 UTC, Zacharis278 commented on registrar/apps/enrollments/data.py
> +        cache.set(PROGRAM_CACHE_KEY_TPL.format(uuid=program_uuid), program)
TIL.  thanks

2019-05-03 13:21 UTC, Zacharis278 commented
@schenedx figured out what I was doing wrong with having a base mixin for POST/PATCH with `test_*` functions so I fixed that to not use DDT anymore

2019-05-03 13:35 UTC, schenedx approved these changes
👍 All my inline comments are non blocking questions or suggestions

2019-05-03 13:35 UTC, schenedx commented on registrar/apps/api/v1/views.py
> +                curriculum = next(c for c in curricula if c['is_active'] is True)
#NIT This is being invoked twice. I can see this being a utility function that can be used in the future?

2019-05-03 13:35 UTC, schenedx commented on registrar/apps/enrollments/data.py
> +PROGRAM_CACHE_KEY_TPL = 'program-{uuid}'
Should this be moved to the constants.py file @jansenk merged in?

2019-05-03 13:35 UTC, schenedx commented on registrar/apps/enrollments/tests/test_data.py
> +    program_uuid = uuid.uuid4().hex[0:10]
Why do we only need the `hex` representation of the first 11 characters? Why not just take `uuid.uuid()` at its face value?

2019-05-03 13:51 UTC, Zacharis278 commented on registrar/apps/api/v1/views.py
> +                curriculum = next(c for c in curricula if c['is_active'] is True)
opted to leave these separate since it's a temp workaround and the cases are _slightly_ different.

2019-05-03 13:57 UTC, Zacharis278 commented on registrar/apps/enrollments/tests/test_data.py
> +    program_uuid = uuid.uuid4().hex[0:10]
overly liberal with copypasta, fixed

2019-05-03 14:57 UTC, iloveagent57 commented on registrar/apps/enrollments/data.py
> +PROGRAM_CACHE_KEY_TPL = 'program-{uuid}'
A minor suggestion about cache keys: a pattern I really like, especially for keeping lines shorter, is to use both a template like you have plus a helper function:
```python
def program_cache_key(program_uuid):
    return PROGRAM_CACHE_KEY_TPL.format(uuid=program_uuid)
```

2019-05-03 15:00 UTC, iloveagent57 commented on registrar/apps/enrollments/tests/test_data.py
> +            json={'message': 'everything is broken'},
https://en.wikipedia.org/wiki/Planet_Telex

2019-05-03 15:01 UTC, iloveagent57 approved these changes
This LGTM, just one very minor suggestion.

2019-05-03 15:01 UTC, kdmccormick requested changes
Looking really good. Just one suggestion, one question, and one nit.

2019-05-03 15:01 UTC, kdmccormick commented on registrar/apps/api/v1/tests/test_views.py
> +    method = 'POST'
Nice :+1: :+1:

2019-05-03 15:01 UTC, kdmccormick commented on registrar/apps/api/v1/views.py
> +                curriculum = next(c for c in curricula if c['is_active'] is True)
Nit: You can drop the `is True`; `c['is_active']` is already a bool. Same for the other appearance of this.

2019-05-03 15:01 UTC, kdmccormick commented on registrar/apps/api/v1/views.py
> +                pass
If we get a `StopIteration`, wouldn't `curriculum` be `None`? And then wouldn't the for loop raise an error?

2019-05-03 15:01 UTC, kdmccormick commented on registrar/apps/api/v1/tests/test_views.py
> +    def make_request(self, path, data, user):
`AuthRequestMixin.request` is available to call directly.

2019-05-03 15:09 UTC, Zacharis278 commented on registrar/apps/api/v1/views.py
> +                pass
good call

2019-05-03 17:08 UTC, kdmccormick approved these changes

2019-05-03 17:09 UTC, merged