add endpoint to clear program cache
openedx-unsupported/registrar pull request #87
Opened 2019-05-07 20:09 UTC by jansenk

Add endpoint to clear cache

2019-05-09 13:48 UTC, kdmccormick commented
Two thought on the URL --
* Maybe it should go under something like `api/internal/` instead of `api/v1/`, just to emphasize that it's not part of our public API
* From a semantic point of view, `DELETE ../cache` would make more sense than `DELETE ../flush-cache`

2019-05-09 14:03 UTC, kdmccormick requested changes

2019-05-09 14:03 UTC, kdmccormick commented on registrar/apps/api/v1/tests/test_views.py
> +class FlushCacheTests(RegistrarAPITestCase, AuthRequestMixin):
Great tests! One more case I can think of -- flushing the same program twice still results in a 200.

2019-05-09 14:03 UTC, kdmccormick commented on registrar/apps/api/v1/views.py
> +            cache.clear()
We only want to delete the program cache, not the entire cache. Right now we also use the cache for mock jobs, and in the future we might use it for more stuff. I recommend looping through `Program.objects.all()` to delete each cached program by UUID.

2019-05-09 14:03 UTC, kdmccormick commented on registrar/apps/api/v1/mixins.py
> +    staff_only = False
:cool:

2019-05-09 14:03 UTC, kdmccormick commented on registrar/apps/api/v1/views.py
> +class FlushCacheView(ProgramSpecificViewMixin, APIView):
I feel like the more explicit `FlushProgramCacheView` or `ProgramCacheView` would be preferable, in case we end up using Registrar's cache for stuff that doesn't get flushed by this view.

2019-05-09 14:05 UTC, jansenk commented on registrar/apps/api/v1/views.py
> +            cache.clear()
Oh, my bad. I looked through and was under the impression we didn't use the cache for jobs any more

2019-05-09 20:45 UTC, kdmccormick approved these changes
Good stuff. Approval pending a minor change -- a DELETE response with an empty body should return a 204 No Content.

2019-05-10 14:53 UTC, jansenk commented
> Good stuff. Approval pending a minor change -- a DELETE response with an empty body should return a 204 No Content.

What would the body contain?

2019-05-10 16:44 UTC, merged